#!/usr/bin/env node

require('./bench')({
  times: [
    [1, 10],
    [5, 50],
    [10, 100],
    [50, 500],
    [100, 1000],
    [500, 5000],
    [1000, 10000]
  ],
  prepareOne: (test) => {
    if (test.name === 'noBinding') {
      var target = {
        ctx: {
          count: 0
        }
      }
      return function () {
        target.ctx.count += 1
      }
    }
    return test({
      ctx: {
        count: 0
      }
    })
  },
  run: (bench) => {
    bench(function noBinding (target) {
    })

    bench(function scopeFunction (target) {
      return function () {
        target.ctx.count += 1
      }
    })

    function x (target) {
      target.ctx.count += 1
    }

    bench(function bindFunction (target) {
      return x.bind(null, target)
    })

    function y () {
      this.ctx.count += 1
    }

    bench(function bindThis (target) {
      return y.bind(target)
    })
  }
})
